[client]
showErrorDetails = true

[logger]
level = "info"

[server]
headless = true
runOnSave = false
maxUploadSize = 200

[theme]
base = "light"
primaryColor = "#c0825a"
backgroundColor = "#faf6f1"
secondaryBackgroundColor = "#f0e8df"
textColor = "#3d2e22"
font = "sans serif"
